source "https://rubygems.org"
git_source(:github) {|repo| "https://github.corepo}.git" }

ruby "3.1.2"
gem "bootsnap", require: false
gem "config"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"
gem "rack-cors"
gem "devise"
gem "devise-i18n"
gem "devise_token_auth"
gem "rails", "~> 7.0.4"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "active_model_serializers"
gem "rails-i18n"
gem "kaminari"

group :development, :test do
  gem "letter_opener_web"
  gem "debug"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "factory_bot_rails"
  gem "faker"
  gem "bullet"
end
